FROM ubuntu:bionic

RUN apt-get update && \
	apt-get dist-upgrade -y && \
	apt-get install -y systemd ansible git golang-go && \
	echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
