FROM debian:buster

RUN apt-get update && \
	apt-get dist-upgrade -y && \
	apt-get install -y systemd ansible lsb-release && \
	echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
