- name: aa-enforce nginx
  shell: aa-enforce usr.sbin.nginx
  when: ansible_apparmor["status"] == "enabled"

- name: systemctl restart nginx
  service: name=nginx state=restarted

- name: systemctl reload nginx
  service: name=nginx state=reloaded
