- name: download webvault
  get_url:
    url: https://github.com/dani-garcia/bw_web_builds/releases/download/v2.20.4b/bw_web_v2.20.4b.tar.gz
    checksum: sha256:baa055b385c81d874effd9fe4eaef6a71a6113acd81ff9d2cbebbb715008e820
    dest: /tmp/webvault.tgz
  register: webvault_download

- name: Extract webvault
  unarchive:
    src: /tmp/webvault.tgz
    dest: /var/www/vault.jak-linux.org
    remote_src: true
    extra_opts: --strip-components=1
  when: webvault_download.changed
