- name: download webvault
  get_url:
    url: https://github.com/dani-garcia/bw_web_builds/releases/download/v2.18.1b/bw_web_v2.18.1b.tar.gz
    checksum: sha256:3301d3c78213af61ae052eaa5c3e26dda0a29e924741ad16a7405b9a083b0134
    dest: /tmp/webvault.tgz
  register: webvault_download

- name: Extract webvault
  unarchive:
    src: /tmp/webvault.tgz
    dest: /var/www/vault.jak-linux.org
    remote_src: true
    extra_opts: --strip-components=1
  when: webvault_download.changed
