- name: download webvault
  get_url:
    url: https://github.com/dani-garcia/bw_web_builds/releases/download/v2023.10.0/bw_web_v2023.10.0.tar.gz
    checksum: sha256:17758e5a37af2e1f847d76d3386551c519526884ee06912d9f78d97e61dd52a0
    dest: /tmp/webvault.tgz
  register: webvault_download

- name: Extract webvault
  unarchive:
    src: /tmp/webvault.tgz
    dest: /var/www/vault.jak-linux.org
    remote_src: true
    extra_opts: --strip-components=1
  when: webvault_download.changed
