- name: download webvault
  get_url:
    url: https://github.com/dani-garcia/bw_web_builds/releases/download/v2024.6.2c/bw_web_v2024.6.2c.tar.gz
    checksum: sha256:ff26268b6ff667d7db93891381b029a599aa59f8ecd56c6756ab7205b0e4c854
    dest: /tmp/webvault.tgz
  register: webvault_download

- name: Extract webvault
  unarchive:
    src: /tmp/webvault.tgz
    dest: /var/www/vault.jak-linux.org
    remote_src: true
    extra_opts: --strip-components=1
  when: webvault_download.changed
