---

- name: install dovecot
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - dovecot-imapd
    - dovecot-sieve
    - dovecot-lmtpd
    state: present

- name: install dovecot apparmor profile
  copy: src=etc/apparmor.d/dovecot dest=/etc/apparmor.d/dovecot
  register: dovecot_apparmor

- name: enforce dovecot
  command: aa-enforce /etc/apparmor.d/dovecot
  when: dovecot_apparmor.changed and ansible_apparmor["status"] == "enabled"

- name: esure dovecot is running
  service:
    name: dovecot
    state: started
    enabled: yes

- name: install dovecot-sieve-filters directory
  file:
    dest: /usr/local/lib/dovecot-sieve-filters
    state: directory

- name: install dovecot.conf
  template: src=dovecot.conf.j2 dest=/etc/dovecot/dovecot.conf
  notify: reload dovecot

- name: ufw allow Dovecot Secure IMAP
  ufw:
    rule: limit
    name: Dovecot Secure IMAP

- name: ensure smtp port is open
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 993
    timeout: 1
  delegate_to: localhost
  tags: assert

- name: install certbot deploy hook
  copy:
    content: |
      #!/bin/sh
      systemctl reload dovecot
    dest: /etc/letsencrypt/renewal-hooks/deploy/dovecot
    mode: 0755
