- name: install nginx
  apt: name=postfix state=present
  become: true
- service:
    name: postfix
    state: started
    enabled: yes
  become: true
  name: ensure postfix is running
- name: install postfix master.cf
  copy: src=etc/postfix/master.cf dest=/etc/postfix/master.cf
  become: true
  register: postfix_master_cf
- when: postfix_master_cf.changed
  service:
    name: postfix
    state: reloaded
  become: true

# Open ports
- ufw: rule=allow name=Postfix
  become: true
- ufw: rule=allow name="Postfix Submission"
  become: true
# Check availability
- wait_for:
    host: "{{ inventory_hostname }}"
    port: 25
    timeout: 1
  delegate_to: localhost
  name: ensure smtp port is open
- wait_for:
    host: "{{ inventory_hostname }}"
    port: 587
    timeout: 1
  delegate_to: localhost
  name: ensure submit port is open
