- name: install nginx
  apt: name=postfix state=present
- service:
    name: postfix
    state: started
    enabled: yes
  name: ensure postfix is running

- name: install postfix master.cf
  copy: src=etc/postfix/master.cf dest=/etc/postfix/master.cf
  register: postfix_master_cf

- name: install postfix main.cf
  template: src=main.cf.j2 dest=/etc/postfix/main.cf
  register: postfix_main_cf

- when: postfix_master_cf.changed or postfix_main_cf.changed
  service:
    name: postfix
    state: reloaded

# Open ports
- ufw: rule=allow name=Postfix
- ufw: rule=limit name="Postfix Submission"
# Check availability
- wait_for:
    host: "{{ inventory_hostname }}"
    port: 25
    timeout: 1
  delegate_to: localhost
  name: ensure smtp port is open
  tags: assert
- wait_for:
    host: "{{ inventory_hostname }}"
    port: 587
    timeout: 1
  delegate_to: localhost
  name: ensure submit port is open
  tags: assert
