---

- name: Add rspamd apt key
  apt_key:
    url: https://rspamd.com/apt-stable/gpg.key
    keyring: /etc/apt/trusted.gpg.d/rspamd.gpg
    id: 3FA347D5E599BE4595CA2576FFA232EDBF21E25E

- name: Add rspamd repository
  apt_repository:
    repo: deb [arch=amd64] http://rspamd.com/apt-stable/ {{ ansible_lsb.codename | default(ansible_distribution_release) }} main
    state: present
    filename: rspamd
    update_cache: true

- name: install rspamd apparmor profile
  copy:
    src: etc/apparmor.d/usr.bin.rspamd
    dest: /etc/apparmor.d/usr.bin.rspamd
  notify:
    - aa-enforce rspamd
    - restart rspamd

- name: create rspamd configuration directory
  file:
    path: /etc/rspamd/local.d/
    state: directory
    mode: 0755

- name: install rspamd configuration
  copy:
    src: etc/rspamd/local.d/{{item}}
    dest: /etc/rspamd/local.d/{{item}}
  loop:
    - actions.conf
    - classifier-bayes.conf
    - milter_headers.conf
    - redis.conf
  notify:
    - restart rspamd

- name: remove rspamd.local.lua
  file:
    path: etc/rspamd/rspamd.local.lua
    state: absent
  notify:
    - restart rspamd

- name: install rspamd and redis
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - rspamd
    - redis

- name: Ensure that rspamd is running
  service:
    name: rspamd
    state: started
    enabled: yes
