- name: install weechat, tmux, mosh
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - weechat
    - weechat-plugins
    - tmux
    - mosh
- name: Add weechat group
  group:
    name: weechat
- name: Add weechat user
  user:
    name: weechat
    group: weechat
    create_home: true
- name: install weechat systemd unit file
  copy: src=etc/systemd/system/weechat.service dest=/etc/systemd/system/weechat.service
  register: weechatservice
- when: weechatservice.changed
  systemd:
    daemon_reload: yes
- name: install weechat apparmor
  copy: src=etc/apparmor.d/usr.bin.weechat.apparmor dest=/etc/apparmor.d/usr.bin.weechat
  register: weechatapparmor
- name: enforce weechat profile
  shell: aa-complain "$file"
  when: weechatapparmor.changed
  register: weechatenforced
- name: ensure weechat is running
  service:
    name: weechat
    state: started
    enabled: yes
- name: restart weechat
  service:
    name: weechat
    state: restarted
  when: weechatenforced.changed or weechatservice.changed
- name: Check if weechat is running and enforced
  shell: ps auxZ | grep weechat | grep -v grep | grep .
  changed_when: false
  register: weechat is confined
- shell: cat /home/weechat/.weechat/relay.conf
  register: weechat_relay_conf
  changed_when: false
- name: add weechat relay
  shell: |
    echo '*/set relay.network.bind_address "::ffff:127.0.0.1"' >> /home/weechat/.weechat/weechat_fifo
    echo '*/relay add weechat 9000' >> /home/weechat/.weechat/weechat_fifo
    echo '*/save relay' >> /home/weechat/.weechat/weechat_fifo
  when:
    weechat_relay_conf.stdout.find('weechat = 9000') == -1 or weechat_relay_conf.stdout.find('bind_address = "::ffff:127.0.0.1"') == -1
- ufw: rule=allow name=mosh
- wait_for:
    host: "127.0.0.1"
    port: 9000
    timeout: 1
  name: ensure weechat port is open

- name: Ensure weechat relay port is not open to public
  wait_for: host="{{ inventory_hostname }}" port=9000 timeout=1 state=stopped
  delegate_to: localhost
  when: inventory_hostname != "localhost"
