- name: install weechat, tmux, mosh
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - weechat
    - tmux
    - mosh
    - apparmor-utils
  become: true
- name: Add weechat group
  group:
    name: weechat
  become: true
- name: Add weechat user
  user:
    name: weechat
    group: weechat
    create_home: true
  become: true
- name: install weechat systemd unit file
  copy: src=etc/systemd/system/weechat.service dest=/etc/systemd/system/weechat.service
  become: true
  register: weechatservice
- when: weechatservice.changed
  systemd:
    daemon_reload: yes
  become: true
- name: install weechat apparmor
  copy: src=etc/apparmor.d/usr.bin.weechat.apparmor dest=/etc/apparmor.d/usr.bin.weechat
  become: true
  register: weechatapparmor
- name: enforce weechat profile
  shell: aa-complain "$file"
  become: true
  when: weechatapparmor.changed
  register: weechatenforced
- name: ensure weechat is running
  service:
    name: weechat
    enabled: yes
  become: true
- name: restart weechat
  service:
    name: weechat
    state: restarted
  become: true
  when: weechatenforced.changed or weechatservice.changed
- name: Check if weechat is running and enforced
  shell: ps auxZ | grep weechat | grep -v grep | grep .
  changed_when: false
  register: weechat is confined
- name: add weechat relay
  shell: |
    echo '*/set relay.network.bind_address "::ffff:127.0.0.1"' >> /home/weechat/.weechat/weechat_fifo
    echo '*/relay add weechat 9000' >> /home/weechat/.weechat/weechat_fifo
    echo '*/save relay' >> /home/weechat/.weechat/weechat_fifo
  become: true
- wait_for:
    host: "127.0.0.1"
    port: 9000
    timeout: 1
  name: ensure weechat port is open
