- name: install weechat, tmux, mosh
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - weechat
    - weechat-plugins
    - tmux
    - mosh


# Discretionary access control
- name: Add weechat group
  group: name=weechat
- name: Add weechat user
  user: name=weechat group=weechat create_home=true

# Mandatory access control
- name: install weechat apparmor
  copy: src=etc/apparmor.d/usr.bin.weechat.apparmor dest=/etc/apparmor.d/usr.bin.weechat
  notify:
    - aa-enforce weechat
    - systemctl restart weechat

# Configure service
- name: install weechat systemd unit file
  copy: src=etc/systemd/system/weechat.service dest=/etc/systemd/system/weechat.service
  notify:
    - systemctl daemon-reload
    - systemctl restart weechat

- name: ensure weechat is running
  service: name=weechat state=started enabled=true

- name: Check if weechat is running and enforced
  shell: ps auxZ | grep weechat | grep -v grep | grep .
  changed_when: false

# Wait for weechat to generate relay conf and fifo so we can configure relay
- name: Check that relay.conf exists
  wait_for: path=/home/weechat/.weechat/relay.conf timeout=1
- name: Check that control fifo exists
  wait_for: path=/home/weechat/.weechat/weechat_fifo timeout=1

- shell: cat /home/weechat/.weechat/relay.conf
  register: weechat_relay_conf
  changed_when: false

- name: add weechat relay
  shell: |
    echo '*/set relay.network.bind_address "::ffff:127.0.0.1"' >> /home/weechat/.weechat/weechat_fifo
    echo '*/relay add weechat 9000' >> /home/weechat/.weechat/weechat_fifo
    echo '*/save relay' >> /home/weechat/.weechat/weechat_fifo
  when:
    weechat_relay_conf.stdout.find('weechat = 9000') == -1 or weechat_relay_conf.stdout.find('bind_address = "::ffff:127.0.0.1"') == -1

# Configure firewall and check that ports work
- name: ufw limit mosh
  ufw: rule=limit name=mosh

- name: ensure weechat port is open
  wait_for: host=127.0.0.1 port=9000 timeout=1
  tags: assert

- name: Ensure weechat relay port is not open to public
  wait_for: host="{{ inventory_hostname }}" port=9000 timeout=1 state=stopped
  delegate_to: localhost
  when: inventory_hostname != "localhost"
  tags: assert
