# Configure apt
- name: make sure apt pipelining is enabled
  file: name=/etc/apt/apt.conf.d/90cloud-init-pipelining state=absent

# Configure entropy generation
- name: check for hardware random number generator
  stat: path=/dev/hwrng
  register: hwrng_stat

- name: install haveged
  apt: name=haveged state=present
  when: hwrng_stat.stat.exists == false

- name: install rng-tools
  apt: name=rng-tools state=present
  when: hwrng_stat.stat.exists == true

# Install other stuff
- name: install ca-certificates
  apt: name=ca-certificates state=present

- name: install apparmor
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apparmor-utils
    - apparmor-profiles

- include: ufw.yml
- include: ssh.yml
