# Configure apt
- name: make sure apt pipelining is enabled
  file: name=/etc/apt/apt.conf.d/90cloud-init-pipelining state=absent

# Install packages
- name: install haveged
  apt: name=haveged state=present

- name: install ca-certificates
  apt: name=ca-certificates state=present

- name: install apparmor
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apparmor-utils
    - apparmor-profiles

- include: ufw.yml
- include: ssh.yml
