- name: install openssh-server
  apt: name=openssh-server state=present
  become: true
- service:
    name: ssh
    state: started
    enabled: yes
  become: true
  name: ensure openssh-server is running
- name: check for ssh
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    timeout: 1
  delegate_to: localhost
