# Configure SSH
- name: install openssh-server
  apt: name=openssh-server state=present

- name: ensure openssh-server is running
  service: name=ssh state=started enabled=true

- name: ufw limit openssh
  ufw: rule=limit name=OpenSSH

- name: Disable password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^(#\s*)?PasswordAuthentication " line="PasswordAuthentication no"
  notify: restart ssh

# Assert that ssh is listening
- name: check that ssh is listening
  wait_for: host="{{ inventory_hostname }}" port=22 timeout=1 search_regex=OpenSSH
  delegate_to: localhost
