- name: newaliases
  command: newaliases

- name: aa-enforce rspamd
  command: aa-enforce usr.bin.rspamd
  when: ansible_apparmor["status"] == "enabled"

- name: restart rspamd
  service:
    name: rspamd
    state: restarted
