- name: install nginx
  apt: name=nginx state=present
  become: true
- service:
    name: nginx
    state: started
    enabled: yes
  become: true
- ufw: rule=allow name="Nginx Full"
  become: true
- wait_for:
    host: "{{ inventory_hostname }}"
    port: 443
    timeout: 1
  delegate_to: localhost
- wait_for:
    host: "{{ inventory_hostname }}"
    port: 80
    timeout: 1
  delegate_to: localhost
