- name: install nginx
  apt: name=nginx state=present

- name: install apparmor profile
  copy: src=etc/apparmor.d/usr.sbin.nginx dest=/etc/apparmor.d/usr.sbin.nginx
  notify:
    - aa-enforce nginx
    - systemctl restart nginx

- service:
    name: nginx
    state: started
    enabled: yes
- ufw: rule=allow name="Nginx Full"
- wait_for:
    host: "{{ inventory_hostname }}"
    port: 80
    timeout: 1
  delegate_to: localhost
